### ISSUE TITLE
Enemy pathfinding to player flag/to player

### ISSUE THREAD

**Issue by ady-1811** [dms-akshat/godot_battle_city#13]
1. Implement a Finite State Machine in the enemy scene to have 3 states
2. State I - Seeking (The enemy is going to the flag)
3. State II - Flag Firing (The enemy is close to the flag and is firing)
4. State III - The enemy has encountered the player and is firing at the player instead

(The enemy should prioritize on firing at the player instead of the flag)

**Comment by poolsgithub** [comment]
1. we make an idle state 0 where it moves randomly and fires for some time like 3 to 4 sec
2. we have flag seeking as state 1
3. we have the enemy attacking as state 2 when it is in the range
4. the firing will be going on automatically from timer and respective direction at the movement
5. we make the enemy switch to idle if they are about to collide
